// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitTags.VSIX
{
    static class Vsix
    {
        public const string Id = "dc5bf021-bbf7-4171-a987-b0cd615a1311";
        public const string Name = "Git Tags";
        public const string Description = @"Easiest way to view/add/delete/edit tags in a Git repo";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "Luminous Software Solutions";
        public const string Tags = "";
    }
}
