// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitTags.Package
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageGuidString = "6359da17-6477-4e9c-8e73-7d05ea8a33a1";
        public const string OptionsDialogPageString = "6bf7c9fa-8e42-4673-83cb-288efe5ae3b5";
        public const string PackageCommandSetString = "4eac4e23-4909-4dac-9d6e-819bdc861480";
        public static Guid PackageGuid = new Guid(PackageGuidString);
        public static Guid OptionsDialogPage = new Guid(OptionsDialogPageString);
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageToolbar = 0xA001;
        public const int PackageMenu = 0xA002;
        public const int CodeEditorGroup = 0xB000;
        public const int SolutionNodeGroup = 0xC000;
        public const int ProjectNodeGroup = 0xD000;
        public const int OptionsGroup = 0x0950;
        public const int OptionsCommands = 0x0952;
        public const int OptionsCommand = 0x0953;
    }
}
