// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitTags.Package
{
    static class Vsix
    {
        public const string Id = "db058027-44b4-4bf3-a383-1bea20098df8";
        public const string Name = "Git Tags (package)";
        public const string Description = @"Easiest way to view/add/delete/edit tags in a Git repo";
        public const string Language = "en-US";
        public const string Version = "0.1.1";
        public const string Author = "Lumnous Software Solutions";
        public const string Tags = "";
    }
}
